### ISSUE TITLE
Node is not getting removed from pendingStartupNodes

### ISSUE THREAD

**Issue by lenny1806** [mhardin/SeleniumGridScaler#17]
The instanceId-Key got removed in [_node.linux.json_](https://github.com/mhardin/SeleniumGridScaler/blob/master/src/main/resources/node.linux.json) and [_node.windows.json_](https://github.com/mhardin/SeleniumGridScaler/blob/master/src/main/resources/node.windows.json) (https://github.com/mhardin/SeleniumGridScaler/commit/437ac6df49af9029a113c2c0240dc665f3c521ce#diff-93ee22ee40521f20359f6fae31902502) . Because of that new started nodes are not getting removed from the **pendingStartupNodes-Map** in [AutomationPendingNodeRegistryTask.java ](https://github.com/mhardin/SeleniumGridScaler/blob/master/src/main/java/com/rmn/qa/task/AutomationPendingNodeRegistryTask.java#L77)

Adding the instanceID to the custom-config should solve the issue.

**Comment by mhardin** [comment]
@lenny1806 I merged your PR over.  Thanks for finding this and fixing the issue.
