### ISSUE TITLE
Option to specify the number of chrome instances

### ISSUE THREAD

**Issue by discobean** [mhardin/SeleniumGridScaler#19]
Hi,

Is there a way to specify the number of chrome drivers to startup per instance?  

Currently it is 5 but I'd like to use larger instances and go to 10 per host.

**Comment by mhardin** [comment]
@discobean you'll have to modify the source files and rebuild the JAR to support this functionality.

**Comment by discobean** [comment]
Yep I figured as much :P thanks for the great library
