### ISSUE TITLE
Other cloud possibilities?

### ISSUE THREAD

**Issue by zonArt** [mhardin/SeleniumGridScaler#20]
Hi, this looks really interesting for having an elastic grid. I'm wondering how easy it would be to make it pluggable on openstack, azure or even on a kubernetes cluster. What do you think, is it something you're planning to do ? Sorry I haven't look close enough to the code to see if it is strongly linked to aws or if it could be generic to welcome other "linkage".

**Comment by mhardin** [comment]
@zonArt thanks for the interest.  The project is unfortunately only compatible with AWS and no current plans on the roadmap to integrate with other cloud providers.
